export const PATIENT_LIST = 'PATIENT_LIST'
export const PATIENT_DATA = 'PATIENT_DATA'

export const PATIENT_MEASURE_LIST = 'PATIENT_MEASURE_LIST'
export const PATIENT_MEASURE_DATA = 'PATIENT_MEASURE_DATA'